export const avatarMap = {
  Alice: 'https://ftp.goit.study/img/avatars/18.jpg',
  Bob: 'https://ftp.goit.study/img/avatars/28.jpg',
  // Eve: '../public/image Eve.jpg',
  // Frank: '../public/image Frank.jpg',
  // Grace: '../public/image Grace.jpg',
  // Henry: '../public/image Henry.jpg',
  // Alex: '../public/image Alex.jpg',
  // Emily: '../public/image Emily.jpg',
  Sophia: 'https://ftp.goit.study/img/avatars/23.jpg',
  Oliver: 'https://ftp.goit.study/img/avatars/22.jpg',
  Liam: 'https://ftp.goit.study/img/avatars/26.jpg',
  Mia: 'https://ftp.goit.study/img/avatars/30.jpg',
  Sophie: 'https://ftp.goit.study/img/avatars/8.jpg',
  Daniel: 'https://ftp.goit.study/img/avatars/11.jpg',
  Ethan: 'https://ftp.goit.study/img/avatars/13.jpg',
  Ava: 'https://ftp.goit.study/img/avatars/16.jpg',
  Olivia: 'https://ftp.goit.study/img/avatars/12.jpg',
  Noah: 'https://ftp.goit.study/img/avatars/24.jpg',
  Benjamin: 'https://ftp.goit.study/img/avatars/17.jpg',
  Jacob: 'https://ftp.goit.study/img/avatars/15.jpg',
};
